version: '2'
maintener: [David Wahyu]
services:
    odoo12:
        image: odoo:12.0
        depends_on:
            - db
        ports:
            - "8012:8069"
        volumes:
            - ./my-addons:/mnt/extra-addons/
            - ./config:/etc/odoo/

    db:
        image: postgres:10
        ports:
            - "54321:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
