version: '3'
services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD={pass}
      - POSTGRES_USER={user}

  odoo12:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8088:8069"
    volumes:
      - ./my-addons:/mnt/extra-addons/
      - ./config:/etc/odoo/
      
