version: '3'
services:
    odoo12:
        image: odoo:12.0
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - ./my-addons:/mnt/extra-addons/
            - ./config:/etc/odoo/

    db:
        image: postgres:10
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
